workflows:
  android-workflow:
    name: Shofyou Independent Build
    environment:
      groups:
        - production
    scripts:
      - name: Remove Median Branding
        script: |
          # حذف ملفات الواجهة التي تظهر فيها الرسالة
          find . -name "launch_screen.xml" -delete
          find . -name "activity_launch.xml" -delete
          # التأكد من اسم التطبيق الظاهري
          find . -name "strings.xml" -exec sed -i '' 's/[Mm]edian/Shofyou/g' {} +
      - name: Generate My Keystore
        script: |
          keytool -genkey -v -keystore shofyou.keystore -alias $CM_KEY_ALIAS -keyalg RSA -keysize 2048 -validity 10000 -storepass $CM_KEYSTORE_PASSWORD -keypass $CM_KEY_PASSWORD -dname "CN=Shofyou, OU=App, O=Shofyou, L=City, S=State, C=US"
      - name: Set Permissions
        script: chmod +x gradlew
      - name: Build Signed App Bundle (AAB) & APK
        script: |
          ./gradlew assembleRelease bundleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/shofyou.keystore \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
      - "**/build/outputs/bundle/**/*.aab"
      - "*.keystore"
